spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    p6spy:
      enable-logging: true
      multiline: true

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
        format_sql: true

    open-in-view: false
    show-sql: true




decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
    datasource-proxy:
      multiline: true
      json-format: true
